### ISSUE TITLE
Tooltips on hover

### ISSUE THREAD

**Issue by abhy3** [smartinsightsfromdata/rd3pie#1]
Is there any way to add tooltips on hover of pie chart as present here: http://d3pie.org/#generator-tooltips ?

**Comment by smartinsightsfromdata** [comment]
@abhy3 Apologies, I left this package aside without much enhancement.  

at the very least I need to update the underlying  javascript library (from 0.1.1 to 0.1.8!).

I will do it in the next couple of days and let you know.

**Comment by smartinsightsfromdata** [comment]
@abhy3  Try rd3pie version 0.1.8 (aligned to the latest d3pie version).

For the time being I've implemented the `caption` type of tooltip.  You need to add a column "caption" to the data frame and this content is displayed when you hover on a particular slice.

this is aligned to the example 1 at [d3pie](http://d3pie.org/website/examples/tooltips.html)

There is another type of tooltips, `placeholder` where you can refer to different fields like the calculate percentage etc. This is not implemented for the time being (as it is not strictly speaking necessary, having the `caption`).

Would you be so kind to let me know if this is enough for your use case?

**Comment by abhy3** [comment]
@smartinsightsfromdata Thanks for this quick change. Yes this worked for me. I needed to show values on hover and I can do that by placing them in caption column.

The issue that I am facing now is to change the color of the slices. The biggest slice in my pie is a bright yellow which does not look good and also the percent written over it is not readable. I need to keep colors inline with other charts.

I checked this in the java script library also at http://d3pie.org/#generator. There it has option to change the color of labels but not of slices of pie. Is this possible with this chart?

**Comment by abhy3** [comment]
Found [this](http://timelyportfolio.github.io/rChartsExtra/d3pie/) implementation by @timelyportfolio where colors are set explicitly but it does not seems to have an option for tooltip.

**Comment by smartinsightsfromdata** [comment]
@abhy3 If you add to your data frame a column named `color`, containing the colors you want, it will override the colors automatically chosen by the package. 

Please note that if you go this way, you need to specify the colour for each label item (otherwise the associated slice will be displayed black).

The format needs to be the "classic" javascript one, e.g.:

``` js
"#00aa00"
```

**Comment by abhy3** [comment]
@smartinsightsfromdata  this works great. Thanks.
